addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.11")
addSbtPlugin("io.crashbox"       % "sbt-gpg"     % "0.2.0")
addSbtPlugin("org.scala-js"      % "sbt-scalajs" % "0.6.28")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "2.5")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
