addSbtPlugin("com.jsuereth"      % "sbt-pgp"     % "1.1.2")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.9")
addSbtPlugin("org.scala-js"      % "sbt-scalajs" % "0.6.23")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "2.3")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.5.0")
